version: "3"

volumes:
  kong_data: {}

networks:
  go_network:
    driver: bridge

services:
  kong:
    build:
      context: ../
    volumes:
      - ./:/cfgs/
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: info
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_PROXY_LISTEN: '0.0.0.0:8000'
      KONG_DATABASE: 'off'
      KONG_GO_PLUGINS_DIR: /usr/local/kong
      KONG_PLUGINS: midnight
      KONG_DECLARATIVE_CONFIG: /cfgs/change-pokemon-type.yml
    networks:
      - go_network
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"